# -*- coding: utf-8 -*-
"""Kaggle_Practice_Codes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12mEXgsankzVMQQG5wysHndAvFgNHaDBT
"""

example_dict = {1: "value1", 2: "value2", 3:"value1" }
print(example_dict.items())

example_list = [1,2,3,4,5,5]
set_example1 = set(example_list)
example_list2 = [3,4,5,6,7,8]
set_example2 = set(example_list2)
print(set_example1.intersection(set_example2))

#Comprehension

example_list4 = [item*2 for item in example_list if item*2 <= 8 ]
print(example_list4)

example_dict2 = {value:key for key,value in example_dict.items()}
print(example_dict2)

a = 12
b = 15
print("This number is {1} next number is {1}".format(a,b))

variable = input("Enter the number here: ")
print(variable)

list1 = [1,2,3,4,5,5,6,7,7,8]
set1 = set(list1)
list1 = list(set1)
dict1 = {item: item**2 for item in list1}
print(dict1.items())

if __name__ == "__main__":
  nums = [1,2,4,5,7,10]
  def has_lucky_number(nums:list) -> str:
    a = 0 
    for i in nums:
      if i%7 == 0:
        a = 1
        break
      else:
        a = 0
    if a == 1:
      return "this is a lucky list."
    else:
      return "unlucky list1."

  string = has_lucky_number(nums)
  print(string)

def is_valid_zip(s:str) -> bool:
  flg = True
  if (len(s) == 5):
    c = list(s)
    for item in c:
      if  not (item.isdigit()):
        flg = False
        break
  else:
    flg = False

  return flg



if __name__ == "__main__":
  zip_code = "1234a"
  zip_code_list = ["12345", "1234a", "1234567", "abcde"]
  zip_code_set = set(zip_code_list)
  zip_code_list1 = list(zip_code_list)
  ret_dict = {}
  for item in zip_code_list:
    ret_value = is_valid_zip(item)
    ret_dict[item] = ret_value

  print(ret_dict.items())





d

def word_search(s: str, words: list) -> bool:
  str_list = s.split()
  for c in str_list:
    for word in words:
      if c == word.lower():
        return True

  return False



if __name__ == "__main__":
  doc_list = ["The Learn Python Challenge Casino", "They bought a car", "Casinoville"]
  word = ["casino", "they"]
  ret_list = []
  for i in range(len(doc_list)):
    index = word_search(doc_list[i].lower(), word)
    if (index):
      ret_list.append(i)

  print(ret_list)

4