# -*- coding: utf-8 -*-
"""LinearRegression(SciKit).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaC49TH8y9POxPWlpdlqAksMSO1h2Vsu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import statsmodels.api as sm

data = pd.read_csv("sample_data/Advertising.csv")

data.head()

data.drop(['Unnamed: 0'], axis = 1)

plt.figure(figsize = (16, 8))
plt.scatter(
    data['TV'],
    data['sales'],
    color = 'pink'
)

plt.xlabel("Cash spent of TV")
plt.ylabel("Sales")

plt.show()

X = data['TV'].values.reshape(-1,1)
y = data['sales'].values.reshape(-1,1)

reg = LinearRegression()
reg.fit(X, y)

print(reg.coef_)
print(reg.intercept_)

prediction = reg.predict(X)

plt.figure(figsize = (16, 8))
plt.scatter(
    data['TV'],
    data['sales'],
    color = 'red'
)

plt.plot(
    data['TV'],
    prediction,
    c = 'blue',
    linewidth = 2
)

plt.xlabel("TV Sales")
plt.ylabel("Sales")

plt.show()

X = data['TV']
y = data['sales']

X_sum = sm.add_constant(X)
est = sm.OLS(y, X_sum)
est2 = est.fit()
print(est2.summary())